version: "3.2"
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'dev'
      MYSQL_DATABASE: 'convertedin'
      MYSQL_USER: 'convertedin'
      MYSQL_PASSWORD: 'convertedin'
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - convertedin

  convertedin:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 8888:80
    networks:
      - convertedin

networks:
  convertedin:
    driver: bridge
volumes:
  my-db:
